USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.5845.2296 YaBrowser/23.9.0.2296 Yowser/2.5 Safari/537.36"
IZVESTIA = "https://iz.ru/"
KOMMERSANT = "https://www.kommersant.ru/"
VEDOMOSTI = "https://www.vedomosti.ru/"
ECHO = "https://echo.msk.ru/personalno/"
NG = "https://ng.ru/politics/"
ZAVTRA = "https://zavtra.ru/blogs/"
MK = "https://www.mk.ru/"