CREATE TABLE TRANSCRIPTS (
    ID integer primary key autoincrement,
	AUTHOR VARCHAR(200),
    DDATE VARCHAR(200),
    URL VARCHAR(200),
	HEADER VARCHAR(200),
	SECTION VARCHAR(200),
	FILENAME VARCHAR(20),
	TRANSCRIPT TEXT,
	SOURCE integer
);
