CREATE TABLE TRANSCRIPTS (
    ID integer primary key autoincrement,
	AUTHOR VARCHAR(200),
    DDATE VARCHAR(200),
    URL VARCHAR(200),
	HEADER VARCHAR(200),
	SECTION VARCHAR(200),
	FILENAME VARCHAR(20),
	TRANSCRIPT TEXT,
	SOURCE integer
);

CREATE VIEW KOMMERSANT AS
SELECT * KOMMERSANT1
UNION ALL
SELECT * KOMMERSANT2
UNION ALL
SELECT * KOMMERSANT3
UNION ALL
SELECT * KOMMERSANT4
UNION ALL
SELECT * KOMMERSANT5
UNION ALL
SELECT * KOMMERSANT6
UNION ALL
SELECT * KOMMERSANT7
UNION ALL
SELECT * KOMMERSANT8
UNION ALL
SELECT * KOMMERSANT9
UNION ALL
SELECT * KOMMERSANT10
UNION ALL
SELECT * KOMMERSANT11
UNION ALL
SELECT * KOMMERSANT12
UNION ALL
SELECT * KOMMERSANT13
UNION ALL
SELECT * KOMMERSANT14
;
