PRAGMA foreign_keys=off;

BEGIN TRANSACTION;
CREATE TABLE GD_COUNT (
	GD_DATE DATE REFERENCES GD_TRANSCRIPTS(HEADER),
	DEMOCRACY DECIMAL(8)
);

INSERT INTO GD_COUNT (GD_DATE, DEMOCRACY)
    SELECT
        HEADER GD_DATE,
        0 DEMOCRACY
FROM GD_TRANSCRIPTS;
COMMIT;

PRAGMA foreign_keys=on;